server:
  error:
    include_stacktrace: on_param

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vlodi_db?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl_auto: update

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
